version: "3"

# Banco para testes

services:
  db:
    image: postgres:12
    container_name: node-cron
    restart: always
    ports:
      - 5430:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gko
